filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true
  
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - "/var/log/myLogs/ss7traceLogs/ss7trace*.log"
  fields: #It works but I am still unsure in regards to if it can be used effectivly or not yet
    fileType : ss7trace
  multiline: #The first part of this pattern is to be able to handle the DEBUG messages
    pattern: '^[0-9]{4}[[:space:]][A-Z,a-z]{3}[[:space:]][0-9]{2}|^RECEIVED|^LINKED|^SENT'
    negate: true
    match: after
    flush_pattern: '\n\n'
#- type: log #This is for testing out if one can read multiple different files of inputs, And it works
#  enabled: true
#  paths:
#  - "/var/log/myLogs/plLogs/*.log"

  
processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~

  
output.logstash:
  hosts: ["logstash:5044"]
  
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
setup.ilm.overwrite: true